
db:
  master:
    client: mysql
    connection:
      host: 127.0.0.1
      port: 3306
      user: triple
      password: "triple123"
      database: triple_main
      dateStrings: TIMESTAMP
      charset: utf8mb4_bin
    pool:
      min: 0
      max: 10
    acquireConnectionTimeout: 60000